name: CDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: AWS CDK GitHub Actions
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'diff'
        actions_comment: false
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
      
    - name: Run a one line example script
      run: echo Hello, World!
