name: CDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: AWS CDK GitHub Actions
      uses: youyo/aws-cdk-github-actions@v2.1.2
      
    - name: Run a one line example script
      run: echo Hello, World!
